# Data Exploration

In [2]:
import pandas as pd
import os

DATA_PATH = "../data/raw"

for file in os.listdir(DATA_PATH):
    if file.endswith(".csv"):
        print(file)

customers.csv
products.csv
orders.csv
marketing.csv
payments.csv
order_items.csv
returns.csv

In [3]:
customers = pd.read_csv(f"{DATA_PATH}/customers.csv")
orders = pd.read_csv(f"{DATA_PATH}/orders.csv")
order_items = pd.read_csv(f"{DATA_PATH}/order_items.csv")
products = pd.read_csv(f"{DATA_PATH}/products.csv")
payments = pd.read_csv(f"{DATA_PATH}/payments.csv")
returns = pd.read_csv(f"{DATA_PATH}/returns.csv")
marketing = pd.read_csv(f"{DATA_PATH}/marketing.csv")

In [4]:
datasets = {
    "customers": customers,
    "orders": orders,
    "order_items": order_items,
    "products": products,
    "payments": payments,
    "returns": returns,
    "marketing": marketing
}

for name, df in datasets.items():
    print(f"{name:15} → {df.shape}")

customers       → (5000, 8)
orders          → (18000, 6)
order_items     → (35427, 11)
products        → (250, 6)
payments        → (18000, 5)
returns         → (1569, 6)
marketing       → (168, 8)

In [5]:
for name, df in datasets.items():
    print(f"\n{name}")
    display(df.head())

customers

,customer_id,customer_name,gender,age,city,signup_date,customer_segment,state
0,10001,Customer_10001,Male,21.0,Delhi,2023-04-18,Regular,Delhi
1,10002,Customer_10002,Female,39.0,Gurugram,2025-07-17,Budget,Haryana
2,10003,Customer_10003,Female,42.0,Hyderabad,2025-02-24,Budget,Telangana
3,10004,Customer_10004,Female,49.0,Gurugram,2024-06-10,Premium,Haryana
4,10005,Customer_10005,Male,42.0,Noida,2024-06-03,Regular,Uttar Pradesh

orders

   order_id  customer_id  order_date sales_channel order_status shipping_city
0    500001        14258  2025-05-19        Direct    Delivered       Kolkata
1    500002        12695  2024-07-10   Paid Search    Delivered         Delhi
2    500003        13130  2025-06-04       Organic    Delivered       Chennai
3    500004        14069  2024-05-14       Organic    Delivered      Gurugram
4    500005        13637  2024-04-29     Affiliate    Delivered        Bhopal

order_items

,order_item_id,order_id,product_id,quantity,unit_price,unit_cost,discount_pct,gross_amount,discount_amount,net_amount,cost_amount
0,900001,500001,20014,1.0,557.20,204.62,10,557.20,55.72,501.48,204.62
1,900002,500001,20004,1.0,10687.99,6945.78,15,10687.99,1603.20,9084.79,6945.78
2,900003,500001,20055,1.0,1146.02,721.90,10,1146.02,114.60,1031.42,721.90
3,900004,500001,20014,4.0,557.20,204.62,0,2228.80,0.00,2228.80,818.48
4,900005,500002,20029,1.0,4040.78,2378.00,10,4040.78,404.08,3636.70,2378.00

products

,product_id,product_name,category,subcategory,unit_price,unit_cost
0,20001,Football 20001,Sports,Football,2034.59,1256.83
1,20002,Storage Box 20002,Home,Storage Box,10282.55,6040.96
2,20003,Perfume 20003,Beauty,Perfume,2966.78,1197.73
3,20004,Yoga Mat 20004,Sports,Yoga Mat,10687.99,6945.78
4,20005,Smartphone 20005,Electronics,Smartphone,1971.82,775.58

payments

   order_id  payment_id payment_method  payment_amount payment_status
0    500001      700001     Debit Card        12846.49           Paid
1    500002      700002    Net Banking         3636.70           Paid
2    500003      700003     Debit Card        22464.42           Paid
3    500004      700004            UPI        27287.97           Paid
4    500005      700005    Credit Card         1487.65           Paid

returns

   return_id  order_id return_date  return_reason refund_status  refund_amount
0     800001    500953  2025-05-11     Size Issue      Refunded        8170.54
1     800002    513911  2025-05-23     Size Issue    Processing       13420.88
2     800003    506098  2025-07-02     Size Issue      Refunded        5170.55
3     800004    507614  2025-12-22   Changed Mind      Refunded       20115.76
4     800005    504200  2024-02-23  Quality Issue      Refunded        5685.93

marketing

,campaign_id,campaign_name,channel,month,spend,impressions,clicks,conversions
0,CAMP001,Summer Sale,Paid Search,2024-01-01,59841.17,1079314,46136,4781
1,CAMP001,Summer Sale,Paid Search,2024-02-01,167815.90,4300818,191520,16157
2,CAMP001,Summer Sale,Paid Search,2024-03-01,64797.34,1276814,20436,1695
3,CAMP001,Summer Sale,Paid Search,2024-04-01,80992.70,1620929,71348,6636
4,CAMP001,Summer Sale,Paid Search,2024-05-01,113285.33,2490146,63558,5124

In [6]:
for name, df in datasets.items():
    print("\n" + "=" * 60)
    print(name.upper())
    print("=" * 60)
    df.info()

============================================================
CUSTOMERS
============================================================
<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       5000 non-null   int64
 1   customer_name     5000 non-null   str
 2   gender            5000 non-null   str
 3   age               4999 non-null   float64
 4   city              4999 non-null   str
 5   signup_date       5000 non-null   str
 6   customer_segment  5000 non-null   str
 7   state             5000 non-null   str
dtypes: float64(1), int64(1), str(6)
memory usage: 312.6 KB

============================================================
ORDERS
============================================================
<class 'pandas.DataFrame'>
RangeIndex: 18000 entries, 0 to 17999
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       18000 non-null  int64
 1   customer_id    18000 non-null  int64
 2   order_date     18000 non-null  str
 3   sales_channel  17999 non-null  str
 4   order_status   18000 non-null  str
 5   shipping_city  18000 non-null  str
dtypes: int64(2), str(4)
memory usage: 843.9 KB

============================================================
ORDER_ITEMS
============================================================
<class 'pandas.DataFrame'>
RangeIndex: 35427 entries, 0 to 35426
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_item_id    35427 non-null  int64
 1   order_id         35427 non-null  int64
 2   product_id       35427 non-null  int64
 3   quantity         35426 non-null  float64
 4   unit_price       35427 non-null  float64
 5   unit_cost        35427 non-null  float64
 6   discount_pct     35427 non-null  int64
 7   gross_amount     35427 non-null  float64
 8   discount_amount  35427 non-null  float64
 9   net_amount       35427 non-null  float64
 10  cost_amount      35427 non-null  float64
dtypes: float64(7), int64(4)
memory usage: 3.0 MB

============================================================
PRODUCTS
============================================================
<class 'pandas.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    250 non-null    int64
 1   product_name  250 non-null    str
 2   category      250 non-null    str
 3   subcategory   250 non-null    str
 4   unit_price    249 non-null    float64
 5   unit_cost     250 non-null    float64
dtypes: float64(2), int64(1), str(3)
memory usage: 11.8 KB

============================================================
PAYMENTS
============================================================
<class 'pandas.DataFrame'>
RangeIndex: 18000 entries, 0 to 17999
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        18000 non-null  int64
 1   payment_id      18000 non-null  int64
 2   payment_method  18000 non-null  str
 3   payment_amount  18000 non-null  float64
 4   payment_status  18000 non-null  str
dtypes: float64(1), int64(2), str(2)
memory usage: 703.3 KB

============================================================
RETURNS
============================================================
<class 'pandas.DataFrame'>
RangeIndex: 1569 entries, 0 to 1568
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   return_id      1569 non-null   int64
 1   order_id       1569 non-null   int64
 2   return_date    1569 non-null   str
 3   return_reason  1569 non-null   str
 4   refund_status  1569 non-null   str
 5   refund_amount  1569 non-null   float64
dtypes: float64(1), int64(2), str(3)
memory usage: 73.7 KB

============================================================
MARKETING
============================================================
<class 'pandas.DataFrame'>
RangeIndex: 168 entries, 0 to 167
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   campaign_id    168 non-null    str
 1   campaign_name  168 non-null    str
 2   channel        168 non-null    str
 3   month          168 non-null    str
 4   spend          168 non-null    float64
 5   impressions    168 non-null    int64
 6   clicks         168 non-null    int64
 7   conversions    168 non-null    int64
dtypes: float64(1), int64(3), str(4)
memory usage: 10.6 KB

In [7]:
for name, df in datasets.items():
    print(f"\n{name.upper()}")
    print(df.isnull().sum())

CUSTOMERS
customer_id         0
customer_name       0
gender              0
age                 1
city                1
signup_date         0
customer_segment    0
state               0
dtype: int64

ORDERS
order_id         0
customer_id      0
order_date       0
sales_channel    1
order_status     0
shipping_city    0
dtype: int64

ORDER_ITEMS
order_item_id      0
order_id           0
product_id         0
quantity           1
unit_price         0
unit_cost          0
discount_pct       0
gross_amount       0
discount_amount    0
net_amount         0
cost_amount        0
dtype: int64

PRODUCTS
product_id      0
product_name    0
category        0
subcategory     0
unit_price      1
unit_cost       0
dtype: int64

PAYMENTS
order_id          0
payment_id        0
payment_method    0
payment_amount    0
payment_status    0
dtype: int64

RETURNS
return_id        0
order_id         0
return_date      0
return_reason    0
refund_status    0
refund_amount    0
dtype: int64

MARKETING
campaign_id      0
campaign_name    0
channel          0
month            0
spend            0
impressions      0
clicks           0
conversions      0
dtype: int64

In [8]:
for name, df in datasets.items():
    print(f"{name:15}: {df.duplicated().sum()} duplicates")

customers      : 0 duplicates
orders         : 0 duplicates
order_items    : 0 duplicates
products       : 0 duplicates
payments       : 0 duplicates
returns        : 0 duplicates
marketing      : 0 duplicates

In [9]:
key_columns = {
    "customers": "customer_id",
    "orders": "order_id",
    "order_items": "order_item_id",
    "products": "product_id",
    "payments": "payment_id",
    "returns": "return_id"
}

for name, key in key_columns.items():
    print(
        f"{name:15} | "
        f"Rows: {len(datasets[name]):6} | "
        f"Unique {key}: {datasets[name][key].nunique():6}"
    )

customers       | Rows:   5000 | Unique customer_id:   5000
orders          | Rows:  18000 | Unique order_id:  18000
order_items     | Rows:  35427 | Unique order_item_id:  35427
products        | Rows:    250 | Unique product_id:    250
payments        | Rows:  18000 | Unique payment_id:  18000
returns         | Rows:   1569 | Unique return_id:   1569

In [10]:
for name, df in datasets.items():
    print(f"\n{name.upper()}")
    display(df.head())

CUSTOMERS

,customer_id,customer_name,gender,age,city,signup_date,customer_segment,state
0,10001,Customer_10001,Male,21.0,Delhi,2023-04-18,Regular,Delhi
1,10002,Customer_10002,Female,39.0,Gurugram,2025-07-17,Budget,Haryana
2,10003,Customer_10003,Female,42.0,Hyderabad,2025-02-24,Budget,Telangana
3,10004,Customer_10004,Female,49.0,Gurugram,2024-06-10,Premium,Haryana
4,10005,Customer_10005,Male,42.0,Noida,2024-06-03,Regular,Uttar Pradesh

ORDERS

   order_id  customer_id  order_date sales_channel order_status shipping_city
0    500001        14258  2025-05-19        Direct    Delivered       Kolkata
1    500002        12695  2024-07-10   Paid Search    Delivered         Delhi
2    500003        13130  2025-06-04       Organic    Delivered       Chennai
3    500004        14069  2024-05-14       Organic    Delivered      Gurugram
4    500005        13637  2024-04-29     Affiliate    Delivered        Bhopal

ORDER_ITEMS

,order_item_id,order_id,product_id,quantity,unit_price,unit_cost,discount_pct,gross_amount,discount_amount,net_amount,cost_amount
0,900001,500001,20014,1.0,557.20,204.62,10,557.20,55.72,501.48,204.62
1,900002,500001,20004,1.0,10687.99,6945.78,15,10687.99,1603.20,9084.79,6945.78
2,900003,500001,20055,1.0,1146.02,721.90,10,1146.02,114.60,1031.42,721.90
3,900004,500001,20014,4.0,557.20,204.62,0,2228.80,0.00,2228.80,818.48
4,900005,500002,20029,1.0,4040.78,2378.00,10,4040.78,404.08,3636.70,2378.00

PRODUCTS

,product_id,product_name,category,subcategory,unit_price,unit_cost
0,20001,Football 20001,Sports,Football,2034.59,1256.83
1,20002,Storage Box 20002,Home,Storage Box,10282.55,6040.96
2,20003,Perfume 20003,Beauty,Perfume,2966.78,1197.73
3,20004,Yoga Mat 20004,Sports,Yoga Mat,10687.99,6945.78
4,20005,Smartphone 20005,Electronics,Smartphone,1971.82,775.58

PAYMENTS

   order_id  payment_id payment_method  payment_amount payment_status
0    500001      700001     Debit Card        12846.49           Paid
1    500002      700002    Net Banking         3636.70           Paid
2    500003      700003     Debit Card        22464.42           Paid
3    500004      700004            UPI        27287.97           Paid
4    500005      700005    Credit Card         1487.65           Paid

RETURNS

   return_id  order_id return_date  return_reason refund_status  refund_amount
0     800001    500953  2025-05-11     Size Issue      Refunded        8170.54
1     800002    513911  2025-05-23     Size Issue    Processing       13420.88
2     800003    506098  2025-07-02     Size Issue      Refunded        5170.55
3     800004    507614  2025-12-22   Changed Mind      Refunded       20115.76
4     800005    504200  2024-02-23  Quality Issue      Refunded        5685.93

MARKETING

,campaign_id,campaign_name,channel,month,spend,impressions,clicks,conversions
0,CAMP001,Summer Sale,Paid Search,2024-01-01,59841.17,1079314,46136,4781
1,CAMP001,Summer Sale,Paid Search,2024-02-01,167815.90,4300818,191520,16157
2,CAMP001,Summer Sale,Paid Search,2024-03-01,64797.34,1276814,20436,1695
3,CAMP001,Summer Sale,Paid Search,2024-04-01,80992.70,1620929,71348,6636
4,CAMP001,Summer Sale,Paid Search,2024-05-01,113285.33,2490146,63558,5124

### Missing Values and data types fix

In [11]:
for name, df in datasets.items():
    print(f"\n{name.upper()}")
    
    missing = df.isnull().sum()
    missing = missing[missing > 0]
    
    if len(missing):
        print("Missing values:")
        print(missing)
    else:
        print("No missing values")

CUSTOMERS
Missing values:
age     1
city    1
dtype: int64

ORDERS
Missing values:
sales_channel    1
dtype: int64

ORDER_ITEMS
Missing values:
quantity    1
dtype: int64

PRODUCTS
Missing values:
unit_price    1
dtype: int64

PAYMENTS
No missing values

RETURNS
No missing values

MARKETING
No missing values

In [12]:
for name, df in datasets.items():
    print(f"\n{name.upper()}")
    print(df.dtypes)

CUSTOMERS
customer_id           int64
customer_name           str
gender                  str
age                 float64
city                    str
signup_date             str
customer_segment        str
state                   str
dtype: object

ORDERS
order_id         int64
customer_id      int64
order_date         str
sales_channel      str
order_status       str
shipping_city      str
dtype: object

ORDER_ITEMS
order_item_id        int64
order_id             int64
product_id           int64
quantity           float64
unit_price         float64
unit_cost          float64
discount_pct         int64
gross_amount       float64
discount_amount    float64
net_amount         float64
cost_amount        float64
dtype: object

PRODUCTS
product_id        int64
product_name        str
category            str
subcategory         str
unit_price      float64
unit_cost       float64
dtype: object

PAYMENTS
order_id            int64
payment_id          int64
payment_method        str
payment_amount    float64
payment_status        str
dtype: object

RETURNS
return_id          int64
order_id           int64
return_date          str
return_reason        str
refund_status        str
refund_amount    float64
dtype: object

MARKETING
campaign_id          str
campaign_name        str
channel              str
month                str
spend            float64
impressions        int64
clicks             int64
conversions        int64
dtype: object

#### Converting to Datetime

In [13]:
customers["signup_date"] = pd.to_datetime(
    customers["signup_date"],
    errors="coerce"
)

orders["order_date"] = pd.to_datetime(
    orders["order_date"],
    errors="coerce"
)

returns["return_date"] = pd.to_datetime(
    returns["return_date"],
    errors="coerce"
)

marketing["month"] = pd.to_datetime(
    marketing["month"],
    errors="coerce"
)

In [14]:
for name, df in datasets.items():
    date_cols = df.select_dtypes(include=["datetime"]).columns
    
    if len(date_cols):
        print(f"\n{name}")
        print(df[date_cols].dtypes)

customers
signup_date    datetime64[us]
dtype: object

orders
order_date    datetime64[us]
dtype: object

returns
return_date    datetime64[us]
dtype: object

marketing
month    datetime64[us]
dtype: object

### Handle Age

In [15]:
customers["age"].describe()

count    4999.000000
mean       38.844369
std        12.478721
min        18.000000
25%        28.000000
50%        39.000000
75%        49.000000
max        60.000000
Name: age, dtype: float64

In [16]:
customers[customers["age"].isna()]

,customer_id,customer_name,gender,age,city,signup_date,customer_segment,state
17,10018,Customer_10018,Male,NaN,Hyderabad,2023-06-03,Budget,Telangana

In [17]:
customers["age"] = customers["age"].fillna(
    customers["age"].median()
)

In [18]:
customers["age"] = customers["age"].astype("int64")

### Missing Categorical Values

In [19]:
customers[customers["city"].isna()]

,customer_id,customer_name,gender,age,city,signup_date,customer_segment,state
83,10084,Customer_10084,Male,34,NaN,2025-09-26,Regular,Rajasthan

In [20]:
orders[orders["sales_channel"].isna()]

    order_id  customer_id order_date sales_channel order_status shipping_city
25    500026        12550 2025-03-18           NaN    Delivered     Bengaluru

In [21]:
customers["city"] = customers["city"].fillna("Unknown")

orders["sales_channel"] = orders["sales_channel"].fillna("Unknown")

### Missing product price

In [22]:
products[products["unit_price"].isna()]

   product_id product_name category subcategory  unit_price  unit_cost
9       20010  Jeans 20010  Fashion       Jeans         NaN     861.46

In [23]:
products.loc[
    products["unit_price"].isna(),
    ["product_id", "product_name", "category", "subcategory", "unit_cost"]
]

   product_id product_name category subcategory  unit_cost
9       20010  Jeans 20010  Fashion       Jeans     861.46

In [24]:
products[
    (products["subcategory"] == "Jeans") &
    (products["unit_price"].notna())
][["product_id", "product_name", "unit_price", "unit_cost"]].sort_values("unit_price")

     product_id product_name  unit_price  unit_cost
133       20134  Jeans 20134     4055.28    2160.08
158       20159  Jeans 20159     4841.96    1984.26

In [25]:
products["markup_ratio"] = products["unit_price"] / products["unit_cost"]

products[
    products["unit_price"].notna()
]["markup_ratio"].describe()

count    249.000000
mean       2.034252
std        0.351592
min        1.538775
25%        1.723246
50%        1.995925
75%        2.304999
max        2.835604
Name: markup_ratio, dtype: float64

In [26]:
products[
    (products["category"] == "Fashion") &
    (products["unit_price"].notna())
][
    ["subcategory", "unit_price", "unit_cost", "markup_ratio"]
].sort_values("markup_ratio")

    subcategory  unit_price  unit_cost  markup_ratio
131    Backpack     1481.71     958.89      1.545235
204      Jacket      992.31     642.07      1.545486
203      Jacket     1164.22     744.86      1.563005
182       Dress     2415.51    1541.50      1.566987
118     T-Shirt     6447.76    4051.44      1.591474
100      Jacket      495.50     311.24      1.592019
167     T-Shirt      902.26     559.09      1.613801
235     T-Shirt      798.64     492.51      1.621571
225     T-Shirt     2006.11    1202.04      1.668921
72     Sneakers      672.95     403.06      1.669603
31        Dress      421.54     251.42      1.676637
59     Backpack      794.08     468.82      1.693784
42     Sneakers      506.86     295.74      1.713870
87      T-Shirt     1969.68    1132.48      1.739263
85        Dress     1750.18     990.74      1.766538
67     Backpack      608.21     337.91      1.799917
58     Backpack     1423.46     776.46      1.833269
244      Jacket     2814.05    1526.29      1.843719
133       Jeans     4055.28    2160.08      1.877375
23     Backpack     5806.29    3085.88      1.881567
56     Sneakers     1299.09     681.94      1.904992
36     Sneakers     1734.87     900.11      1.927398
224    Sneakers     1183.96     611.67      1.935619
27      T-Shirt     2140.06    1062.98      2.013265
101     T-Shirt      631.51     312.41      2.021414
239       Dress     5892.88    2880.72      2.045627
16        Dress     1109.27     542.21      2.045831
12     Sneakers     2355.66    1097.00      2.147366
105    Sneakers     5100.65    2361.04      2.160340
37        Dress      780.89     358.20      2.180039
230    Sneakers     1001.94     443.63      2.258504
114    Sneakers     3585.93    1528.09      2.346675
90        Dress     2708.48    1134.09      2.388241
226    Backpack      540.46     225.55      2.396187
15     Sneakers     3654.84    1512.21      2.416887
191    Sneakers     1251.49     516.17      2.424569
158       Jeans     4841.96    1984.26      2.440184
229    Sneakers     4929.39    1876.99      2.626221
88        Dress     6296.83    2350.00      2.679502
228     T-Shirt      451.90     167.11      2.704207

In [27]:
jeans_markup = products[
    (products["subcategory"] == "Jeans") &
    (products["unit_price"].notna())
]["markup_ratio"].median()

jeans_markup

np.float64(2.1587795810440857)

In [28]:
missing_price_mask = products["unit_price"].isna()

products.loc[missing_price_mask, "unit_price"] = (
    products.loc[missing_price_mask, "unit_cost"] * jeans_markup
).round(2)

In [29]:
products.loc[
    products["product_id"] == 20010,
    ["product_id", "product_name", "unit_price", "unit_cost", "markup_ratio"]
]

   product_id product_name  unit_price  unit_cost  markup_ratio
9       20010  Jeans 20010      1859.7     861.46           NaN

In [30]:
products["markup_ratio"] = (
    products["unit_price"] / products["unit_cost"]
).round(3)

In [31]:
products.loc[
    products["product_id"] == 20010
]

,product_id,product_name,category,subcategory,unit_price,unit_cost,markup_ratio
9,20010,Jeans 20010,Fashion,Jeans,1859.7,861.46,2.159

### Missing Quantity

In [32]:
order_items[order_items["quantity"].isna()]

,order_item_id,order_id,product_id,quantity,unit_price,unit_cost,discount_pct,gross_amount,discount_amount,net_amount,cost_amount
31,900032,500020,20152,NaN,1133.67,691.09,0,1133.67,0.0,1133.67,691.09

In [33]:
row = order_items[order_items["order_item_id"] == 900032]

row["gross_amount"] / row["unit_price"]

31    1.0
dtype: float64

In [34]:
order_items.loc[
    order_items["order_item_id"] == 900032,
    "quantity"
] = 1

In [35]:
order_items.loc[
    order_items["order_item_id"] == 900032
]

,order_item_id,order_id,product_id,quantity,unit_price,unit_cost,discount_pct,gross_amount,discount_amount,net_amount,cost_amount
31,900032,500020,20152,1.0,1133.67,691.09,0,1133.67,0.0,1133.67,691.09

## Data Integrity Checks

### Check Foreign keys

In [36]:
# A. Every order should have a valid customer

orders[~orders["customer_id"].isin(customers["customer_id"])]

Empty DataFrame
Columns: [order_id, customer_id, order_date, sales_channel, order_status, shipping_city]
Index: []

In [37]:
orders["customer_id"].isin(customers["customer_id"]).value_counts()

customer_id
True    18000
Name: count, dtype: int64

In [38]:
# B. Every order item should belong to an existing order

order_items[
    ~order_items["order_id"].isin(orders["order_id"])
]

Empty DataFrame
Columns: [order_item_id, order_id, product_id, quantity, unit_price, unit_cost, discount_pct, gross_amount, discount_amount, net_amount, cost_amount]
Index: []

In [39]:
# C. Every order item should reference an existing product

order_items[
    ~order_items["product_id"].isin(products["product_id"])
]

Empty DataFrame
Columns: [order_item_id, order_id, product_id, quantity, unit_price, unit_cost, discount_pct, gross_amount, discount_amount, net_amount, cost_amount]
Index: []

In [40]:
# D. Every payment should reference an existing order

returns[
    ~returns["order_id"].isin(orders["order_id"])
]

Empty DataFrame
Columns: [return_id, order_id, return_date, return_reason, refund_status, refund_amount]
Index: []

In [41]:
# E. Every return should reference an existing order

returns[
    ~returns["order_id"].isin(orders["order_id"])
]

Empty DataFrame
Columns: [return_id, order_id, return_date, return_reason, refund_status, refund_amount]
Index: []

### Validate Quantities

In [42]:
order_items["quantity"].describe()

count    35427.000000
mean         1.377989
std          0.687111
min          1.000000
25%          1.000000
50%          1.000000
75%          2.000000
max          4.000000
Name: quantity, dtype: float64

In [43]:
order_items[
    (order_items["quantity"] <= 0) |
    (order_items["quantity"].isna())
]

Empty DataFrame
Columns: [order_item_id, order_id, product_id, quantity, unit_price, unit_cost, discount_pct, gross_amount, discount_amount, net_amount, cost_amount]
Index: []

### Validate Prices

In [44]:
products[
    (products["unit_price"] <= 0) |
    (products["unit_cost"] <= 0)
]

Empty DataFrame
Columns: [product_id, product_name, category, subcategory, unit_price, unit_cost, markup_ratio]
Index: []

In [45]:
order_items[
    (order_items["unit_price"] <= 0) |
    (order_items["unit_cost"] <= 0)
]

Empty DataFrame
Columns: [order_item_id, order_id, product_id, quantity, unit_price, unit_cost, discount_pct, gross_amount, discount_amount, net_amount, cost_amount]
Index: []

### Validate discount percentages

In [46]:
order_items["discount_pct"].describe()

count    35427.000000
mean        10.259548
std          7.576160
min          0.000000
25%          5.000000
50%         10.000000
75%         15.000000
max         25.000000
Name: discount_pct, dtype: float64

In [47]:
order_items[
    (order_items["discount_pct"] < 0) |
    (order_items["discount_pct"] > 100)
]

Empty DataFrame
Columns: [order_item_id, order_id, product_id, quantity, unit_price, unit_cost, discount_pct, gross_amount, discount_amount, net_amount, cost_amount]
Index: []

### Validate Calculations

In [48]:
# Gross Amount

calculated_gross = (
    order_items["quantity"] *
    order_items["unit_price"]
).round(2)

(order_items["gross_amount"] != calculated_gross).sum()

np.int64(0)

In [49]:
# Discount 

calculated_discount = (
    order_items["gross_amount"] *
    order_items["discount_pct"] / 100
).round(2)

(order_items["discount_amount"] != calculated_discount).sum()

np.int64(0)

In [50]:
# Net Amount

calculated_net = (
    order_items["gross_amount"] -
    order_items["discount_amount"]
).round(2)

(order_items["net_amount"] != calculated_net).sum()

np.int64(0)

In [51]:
from pathlib import Path

PROCESSED_PATH = Path("../data/processed")
PROCESSED_PATH.mkdir(parents=True, exist_ok=True)

In [52]:
products = products.drop(columns=["markup_ratio"])

In [53]:
processed_datasets = {
    "customers": customers,
    "orders": orders,
    "order_items": order_items,
    "products": products,
    "payments": payments,
    "returns": returns,
    "marketing": marketing
}

for name, df in processed_datasets.items():
    df.to_csv(PROCESSED_PATH / f"{name}.csv", index=False)
    print(f"{name}.csv saved → {df.shape}")

customers.csv saved → (5000, 8)
orders.csv saved → (18000, 6)
order_items.csv saved → (35427, 11)
products.csv saved → (250, 6)
payments.csv saved → (18000, 5)
returns.csv saved → (1569, 6)
marketing.csv saved → (168, 8)

In [54]:
for file in PROCESSED_PATH.glob("*.csv"):
    print(file.name)

customers.csv
products.csv
orders.csv
marketing.csv
payments.csv
order_items.csv
returns.csv

In [55]:
for name, df in processed_datasets.items():
    print(
        f"{name:15} | "
        f"Rows: {len(df):,} | "
        f"Missing: {df.isna().sum().sum()}"
    )

customers       | Rows: 5,000 | Missing: 0
orders          | Rows: 18,000 | Missing: 0
order_items     | Rows: 35,427 | Missing: 0
products        | Rows: 250 | Missing: 0
payments        | Rows: 18,000 | Missing: 0
returns         | Rows: 1,569 | Missing: 0
marketing       | Rows: 168 | Missing: 0